//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MobileAppAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class FileTable
    {
        public int Id { get; set; }
        public string SourceFile { get; set; }
        public string DestinationFile { get; set; }
    }
}
